# Generated by Django 4.2.20 on 2025-05-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolverFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=10)),
                ('solution', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
