# Generated by Django 4.2.20 on 2025-05-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_solverfeedback_delete_greeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solverfeedback',
            name='feedback',
            field=models.TextField(),
        ),
    ]
