# Generated by Django 5.2.5 on 2025-08-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_eventsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='username',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
