# Generated by Django 5.2.5 on 2025-08-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_eventsubmission_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='judge',
            field=models.TextField(default='no judge'),
            preserve_default=False,
        ),
    ]
