# Generated by Django 5.2.5 on 2025-08-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_eventsubmission_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
